# Generated by Django 2.0 on 2019-08-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('durga_app', '0002_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('salary', models.FloatField()),
                ('email', models.EmailField(max_length=20)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
    ]
